
neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj
  batch_size: 50

project:
  repo: repos/gr-testbench/
  start_date: #"1 February, 2018"
  end_date: #"30 March, 2018"
  project_id: 'graphrepo-testbench'
  index_code: False
  index_developer_email: True