neo:
  db_url: 192.168.178.75
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/hadoop/
  start_date: "1 January, 2017 00:00"
  end_date: "1 February, 2017 23:59"
  project_id: hadoop