neo:
  db_url: 192.168.178.75
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/hadoop/
  start_date: "1 January, 2017"
  end_date: "1 July, 2017"
  project_id: hadoop
  index_date_nodes: False