neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj
  batch_size: 50

project:
  repo: repos/hadoop/
  start_date: "1 January, 2017 00:00"
  end_date: "1 January, 2018 00:00"
  project_id: hadoop
  index_code: True