neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/kibana/
  start_date: "1 June, 2018 00:00"
  end_date: "1 June, 2019 00:00"
  project_id: kibana
  batch_size: 50
  index_code: True