neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/pydriller/
  start_date: #"1 February, 2018"
  end_date: #"30 March, 2018"
  project_id: 'pydriller'
  batch_size: 50
  index_code: True