neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/pytorch/
  start_date: "1 December, 2019 00:00"
  end_date: "1 May, 2020 00:00"
  project_id: pytorch
  batch_size: 200