neo:
  db_url: 192.168.178.75
  port: 7687
  db_user: neo4j
  db_pwd: neo4jj

project:
  repo: repos/tensorflow/
  start_date: #"1 February, 2018"
  end_date: #"30 March, 2018"
  project_id: 'tensorflow'
  index_date_nodes: False